### PR TITLE
PODB-266 Get the public keyset via a client instead of file_get_contents

### PR DESCRIPTION
**Pull request by dbhynds**
## Summary of Changes

Rather than using `file_get_contents()` to fetch the keyset, use the HTTP client provided in the service provider.

## Testing

I created a branch on our platform which uses these changes and verified the E2E tests pass.

- [x] I have added automated tests for my changes

### CODE REVIEW

**Review by EricTendian — COMMENTED** [review]
Looks good, can you just update the CHANGELOG and UPGRADES files?

**Comment by EricTendian** [comment]
@dbhynds so I'm fine with that, but what I don't understand is why we made a 4.0 release for the logging change then, if it wasn't a breaking change. If going forward we go with the policy you outlined then that works.

**Comment by craigmbooth** [comment]
I'll just weigh in quickly here.  The logging change shouldn't have been a major version release, it was a patch, but we can't undo it.

Going forward we should do semver as well as we are able and reserve major version changes for breaking changes (of which there should be very few!), minor versions for the addition of new functionality and patch versions for bugfixes, internal non-user-facing changes, and small, non-breaking additions that wont impact anybody who has pinned to a minor version

**Review by EricTendian — APPROVED** [review]

**Comment by dbhynds** [comment]
Our E2E tests flagged up some mistakes in my original implementation. Fixed now. Eric, mind taking a look at both of these PRs: https://github.com/packbackbooks/questions/pull/5284.

I wanna make sure both PRs look good before merging this one.

**Review by EricTendian — COMMENTED** [review]
Just one question, otherwise looks good.

**Review by EricTendian — APPROVED** [review]

**Pull request merged**
