### PR TITLE
PODA-7 Rename Interfaces

### PR DESCRIPTION
**Pull request by dbhynds**
## Summary of Changes

This PR renames interfaces to have a consistent naming structure `IAbstractedObject` instead of inconsistent / confusing names like `AbstractedObject` or `AbstractedObjectInterface`

It was totally bugging me, and since we're making breaking changes as part of 2.0, I figured might as well do it now.

## Testing

- [x] I have run `composer test`
- [x] I have run `composer lint-fix`

I updated interfaces on the App API, and tests passed: https://github.com/packbackbooks/questions/pull/4460

### CODE REVIEW

**Review by cophaso — CHANGES_REQUESTED** [review]
A Couple places that need updating, most of them comments. 

https://github.com/packbackbooks/lti-1-3-php-library/blob/ef6f802c3f792e02a2e56935efec33a9dceefbf2/src/LtiMessageLaunch.php#L28-L30

https://github.com/packbackbooks/lti-1-3-php-library/blob/ef6f802c3f792e02a2e56935efec33a9dceefbf2/src/LtiMessageLaunch.php#L54-L55

https://github.com/packbackbooks/lti-1-3-php-library/blob/ef6f802c3f792e02a2e56935efec33a9dceefbf2/src/LtiMessageLaunch.php#L61

https://github.com/packbackbooks/lti-1-3-php-library/blob/ef6f802c3f792e02a2e56935efec33a9dceefbf2/src/LtiOidcLogin.php#L25-L27

**Review by cophaso — CHANGES_REQUESTED** [review]
Missed these.

https://github.com/packbackbooks/lti-1-3-php-library/blob/ef6f802c3f792e02a2e56935efec33a9dceefbf2/src/LtiMessageLaunch.php#L61

**Comment by dbhynds** [comment]
Good catch. I updated the branch for PBQ and am making sure it passes.

**Review by cophaso — APPROVED** [review]
Looks good!

**Pull request merged**
