### PR TITLE
Allow LtiMessgageLaunch validation steps to be modified by tool providers

### PR DESCRIPTION
**Pull request by erikdonohoo**
## Summary of Changes

Hi there. I represent GoReact, a large educational feedback tool. We are adding support for LTI 1.3 and have decided to use your library to help us. In implementing this, we want to make a few modifications that will help us with the validation phases, but unfortunately, all the validation methods in the `LtiMessageLaunch` class are private and therefore cannot be modified by a class that extends it. This change simply makes those private methods protected so an extending class can modify them. We would love to work with you guys and potentially even help support this library if you feel you need extra help. LTI is an important part of what we do so we will be actively interested in the success of this project.

## Testing

- [ ] I have added automated tests for my changes
- [ x] I ran `composer test` before opening this PR
- [ x] I ran `composer lint-fix` before opening this PR

Seeing as how all we are doing here is marking the methods protected, new tests are not really necessary. Let me know if you have concerns with this change.

### CODE REVIEW

**Comment by erikdonohoo** [comment]
Hey is anyone monitoring this project right now that has any feedback for me on this change?

**Comment by erikdonohoo** [comment]
@lin-brian-l @dbhynds I've read in other PRs that sometimes these slip through the cracks as you don't get notified. I'm hoping "pinging" you here helps this get visibility.

**Comment by dbhynds** [comment]
@erikdonohoo Could you provide some additional details about the validation that you're planning to perform that isn't currently being done by the package?

If the validation **is not** specific to your application but is generic to LTI in general, it might be worth just adding that validation to this package.

If the validation **is** something that's unique to your app, I would actually recommend against overriding these methods, but instead doing the validation yourself in the app. The goal of these methods is to determine of the message launch is valid according the LTI standards. Mixing in your own application-logic for validation seems like a separate concern.
4
That's my initial reaction at least. I'd love to hear more about how you're trying to use it.

**Comment by erikdonohoo** [comment]
The validation we intend to do has to do with 1.1 -> 1.3 migrations. Your library is great as far as we've seen for handling 1.3 cleanly, but there isn't much for being able to handle migrations. We intend to do validation during the validationDeployment phase to determine if a before-unseen deployment can be safely auto-added to the DB by verifying things like the `oauth_consumer_key_sign` as well as checking params shared between 1.3 and 1.1 like `tool_consumer_instance_guid`.

Some of that will likely be unique to our app, but we essentially just want to add additional validation during the deployment validation phase on top of what your library already includes.  Let me know your thoughts on this. The advantage of doing it during the deployment phase and not just in our own code after the validate() call is if we do decide to auto-add the deployment we wouldn't have to re-call the validate() pipeline a second time. To complete the validation.

What are your thoughts @dbhynds ?

**Comment by dbhynds** [comment]
Ew 1.1 to 1.3 migrations? I don't envy you. That sounds messy.

So essentially, you're wanting to do something kind of like this?

```php
// psuedocode, this wouldn't actually work
try {
    $message->validate();
} catch (NoDeploymentException $e) {
    if ($requestMatchesKnownLti11Key) {
        // Add a deployment if we recognize the key
        Deployment::create([
            'iss' => $request['iss'],
            'deployment_id' => $request['deployment_id'],
            ..$otherAttributes
        ]);
    }

    // Revalidate the message
    $message->validate();
}
```

Unfortunately, even with the changes in this PR the `$request` property on this object is private and the only place it's set is in the `validate()` function, so even with your PR, you'd still need to call `validate()` again to set the `$request` property.

Here's what I'd recommend:

1. Add a `setRequest()` method to the message object.
2. Update the `validate()` method so that if `isset($this->request)` it ignores the arguments passed to it.
3. Within your app, call `$message->validate()` inside of a `try..catch`. If you catch an exception related to deployments, do whatever you're going to do (add a deployment to the DB if appropriate), then re-call `$message->validate()` similar to the psuedocode above.


```php
    public function setRequest(array $request)
    {
        $this->request = $request;
    }

    public function validate(array $request = null)
    {
        if ($request === null) {
            $request = $_POST;
        }
        if (!isset($this->request) {
            $this->request = $request;
        }


```

This should leave you with some fairly clean application code while not muddying the waters of method inheritance on this object too much. What do you think of this approach?

**Comment by erikdonohoo** [comment]
Haha, indeed it is messy. I don't understand how you and other tool providers are avoiding it. But we intend to be the most robust tool when it comes to 1.1 and 1.3 support, as well as the ability to have a clean and secure migration between the two.

As far as your concern, I don't see how I would need to set request property a second time. Especially if we catch the handle the fact the deployment is missing in the `validateDeployment()` call itself. The request is set at the beginning of the validate call, and even if it throws, it is still set. Here is the psuedocode that helps us eliminate the need to call validate() twice.

```php
    private function validateDeployment()
    {
        if (!isset($this->jwt['body'][LtiConstants::DEPLOYMENT_ID])) {
            throw new LtiException(static::ERR_MISSING_DEPLOYEMENT_ID);
        }

        // Find deployment.
        $client_id = is_array($this->jwt['body']['aud']) ? $this->jwt['body']['aud'][0] : $this->jwt['body']['aud'];
        $deployment = $this->db->findDeployment($this->jwt['body']['iss'], $this->jwt['body'][LtiConstants::DEPLOYMENT_ID], $client_id);

        if (empty($deployment)) {
            // deployment not recognized, try to upgrade or migrate
            // From here, we have access to the launchData
            $deployment = $this->attemptToMigrate($this->getLaunchData());
        }

        if (empty($deployment)) {
            // deployment not recognized, even after attempting to migrate
            throw new LtiException(static::ERR_NO_DEPLOYMENT);
        }

        return $this;
    }
```

This way, the NO_DEPLOYMENT err is only thrown if we really don't recognize it or if we reject the migration for some other reason. Thoughts?

**Comment by dbhynds** [comment]
Are you certain it's safe to auto create deployments? It's been a couple of years since I've worked on this specific area, but I thought that was a security concern.

Have you been certified with IMSGlobal? I thought auto creating deployments was not allowed as part of their certification process but I could be misremembering.

**Comment by erikdonohoo** [comment]
This would only be something done as a part of 1.1 -> 1.3 migrations using the oauth_consumer_key_sign. Otherwise, no they would not be automatically provisioned. But in the case you can ensure a 1.3 launch is from a pre-existing 1.1 customer with a oauth_consumer_key_sign that you can verify, then it should indeed be safe to automatically provision a deployment and skip the manual verification step. In fact, its the ONLY safe way to migrate from 1.1 to 1.3 as any other option that is not that is susceptible to many security holes depending on the LMS and possible social engineering.

**Comment by erikdonohoo** [comment]
We've spent a lot of time researching this and are actually working directly with blackboard and canvas on finalizing their implementations on supporting the `oauth_consumer_key_sign`. We have been flabbergasted honestly that virtually no LMSs had previously supported this part of the spec, but we blame IMSGlobal for not defining it earlier. Very little thought was done to ensure secure migrations from both the LMS side and the Tool side and we have been pushing hard for improvements there with our partnerships. @dbhynds

**Comment by dbhynds** [comment]
Ahah. You're referring to this: https://www.imsglobal.org/spec/lti/v1p3/migr Hm. Ok. We haven't done migrations in the past so this is new territory for me. Let me make sure I understand the process. Can you correct me here?

1. An LMS has an existing LTI 1.1 integration with your app
2. They decide to migrate to 1.3. You provide them some necessary integration info (URLs, etc).
3. They perform a 1.3 launch against your app.
4. You check the `oauth_consumer_key_sign`
5. If it matches you upgrade, them from 1.1 to 1.3 in your app.

Assuming that's right, does the `oauth_consumer_key_sign` then come across in every single LTI launch they perform? Or is it just a one-time thing?

I'm thinking we should actually just add a way to do migrations in this package itself, rather than you having to override the function of these methods.

**Comment by erikdonohoo** [comment]
It does continue coming in future launches, though you would not need it after that initial launch. Migration goes beyond that as well in that the identifiers for a user can change between 1.1 and 1.3 so there is an additional claim for 1.1 params that have changed in 1.3 so you can "re-bind" the identifiers on your side.

As far as supporting migrations in the package, that would be fine, but most logic would be business logic for the tool itself. I don't think it would make much sense to do anything besides something similar to the psuedo-code I offered here, and allow the tool to decide how to verify the migration. 1.1 was very wild west when it came to actually uniquely identifying things, and some schools even shared `tool_consumer_instance_guids` so I don't think you can build a one size fits all solution in the package that will meet every tools unique needs. I think offering a solution like this would be sufficient:

```php
  private function validateDeployment()
  {
        if (!isset($this->jwt['body'][LtiConstants::DEPLOYMENT_ID])) {
            throw new LtiException(static::ERR_MISSING_DEPLOYEMENT_ID);
        }

        // Find deployment.
        $client_id = is_array($this->jwt['body']['aud']) ? $this->jwt['body']['aud'][0] : $this->jwt['body']['aud'];
        $deployment = $this->db->findDeployment($this->jwt['body']['iss'], $this->jwt['body'][LtiConstants::DEPLOYMENT_ID], $client_id);

        if (empty($deployment)) {
            // deployment not recognized, try to upgrade or migrate
            // From here, we have access to the launchData
            $deployment = $this->attemptToMigrate($this->getLaunchData());
        }

        if (empty($deployment)) {
            // deployment not recognized, even after attempting to migrate
            throw new LtiException(static::ERR_NO_DEPLOYMENT);
        }

        return $this;
  }

protected function attemptToMigrate (array $launchData)
{
   // By default, packback doesn't do migration, but tools can implement support for how migration needs to look for them
    return false;
}
```

And then a tool can extend the launchMessage class and implement the attemptToMigrate function themselves. Or something along those lines. What do you think? It would also be nice to add the migration claim to your constants file, `https://purl.imsglobal.org/spec/lti/claim/lti1p1`. @dbhynds ?

**Comment by dbhynds** [comment]
Yeah, now that I think about it, it sounds like it'd be a lot of very tool-specific code. What if we gave the tool the ability to specify an optional callback to handle migrations during launches. So when you receive a launch, you do something like this:

```php
$message = new LtiMessageLaunch(/* yadda yadda */);
$message->setMigrationCallback($callback);
$message->validate($request);

// Then in the LtiMessageLaunch
private function validateDeployment() {
    // blah blah blah try to find the deployment

    if (!isset($deployment) && $this->shouldMigrate()) {
        $deployment = $this->migrationCallback($this->request);
    }

    // blah blah blah, handle no deployment
}

private function shouldMigrate() {
    return isset($this->migrationCallback)
        // needs implementing
        && $this->oauthConsumerKeySignMatchesAnLti11Key();
}
```

Also, I'm in full agreement about adding the migration message claim to the constants.

**Comment by erikdonohoo** [comment]
That could work. I'd prefer if `migrationCallback()` was passed the parsed launchData and not just the raw `$this->request` as that is available at this point. Also, the `oauthConsumerKeySignMatchesAnLti11Key()` would need to be implemented by the tool as well since it would need to interact with their DB somehow to find out if that is a match. @dbhynds

**Comment by erikdonohoo** [comment]
We are actively developing our 1.3 support right now, which is why we are actively looking to get something in here that we can work with as soon as possible. We could always work around it by potentially calling validate() twice, but it would be much cleaner if we could agree on something (hopefully simple) that we can get in to help us meet our needs here. And again, we'd love to help support this library going forward, as we are going to be married to it now. 60% of our customers use LTI and we expect a lot of them to move to 1.3 in the near future as we finalize our support for it. But a solid migration strategy is paramount for us.

**Comment by dbhynds** [comment]
I'm going to go ahead and approve this PR, but I'd love to keep hammering away at this question so we can find a long-term solution. I'll create a separate issue and tag you on it so we can continue the conversation.

**Review by dbhynds — APPROVED** [review]

**Comment by erikdonohoo** [comment]
@dbhynds Sounds great! Thanks for working with me on this. I'd love to keep chatting and come up with a great solution in the library itself. I can start putting something together as we work on our migration code.

**Comment by erikdonohoo** [comment]
Also @dbhynds how often do you tag new releases? To help make this convenient to get via composer, etc?

**Comment by dbhynds** [comment]
I just published a release an hour or so ago, so it should be available. Hopefully that unblocks you for the time being. I've also tagged you on a PR to begin building out a more robust solution. Would you be open to contributing directly on that PR?

**Pull request merged**
